#!/usr/bin/env python3
"""
examples/lid_driven_cavity.py
==============================
End-to-end pre/post-processing example for the lid-driven cavity benchmark.

Workflow
--------
1. Generate the solver TOML configuration (pre-processing).
2. Build a gmsh background mesh of the domain (pre-processing).
3. Generate synthetic solver output for demonstration (stands in for the
   real solver; replace with NpzReader pointing at real output).
4. Produce visualisation plots (post-processing):
   - Velocity magnitude contour
   - Streamlines
   - Vorticity
   - Velocity profile at cavity centreline
5. Compute bulk statistics (post-processing).

Run::

    cd python/
    python3 examples/lid_driven_cavity.py

Outputs are written to  examples/output/lid_cavity/ .
"""

from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / "output" / "lid_cavity"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# 1. Generate solver configuration
# ---------------------------------------------------------------------------
from lbm_pre.config_gen import SolverConfig, reynolds_to_nu

cfg = SolverConfig.lid_driven_cavity(nx=100, ny=100, Re=100.0, U_lid=0.1)
config_path = cfg.write(
    OUTPUT_DIR / "config.toml",
    comment="Lid-driven cavity Re=100  (generated by examples/lid_driven_cavity.py)",
)
print(f"[1/5] Config written → {config_path}")

# ---------------------------------------------------------------------------
# 2. Generate gmsh background mesh
# ---------------------------------------------------------------------------
from lbm_pre.mesh import MeshBuilder

mesh_path = OUTPUT_DIR / "domain.msh"
with MeshBuilder(100, 100).set_mesh_size(5.0) as mb:
    mb.build().write(mesh_path)
info = mb.info() if mb._built else None
print(f"[2/5] Mesh written  → {mesh_path}")
if info is not None:
    print(f"      nodes={info.n_nodes}  elements={info.n_elements}")

# ---------------------------------------------------------------------------
# 3. Generate synthetic "solver output"
# ---------------------------------------------------------------------------
from lbm_post.vtk_reader import make_synthetic_lid_cavity, save_snapshot_npz

snaps_dir = OUTPUT_DIR / "snapshots"
snaps_dir.mkdir(exist_ok=True)
steps = list(range(0, 10001, 1000))
snapshots = []
for s in steps:
    snap = make_synthetic_lid_cavity(nx=100, ny=100, U_lid=0.1, step=s)
    save_snapshot_npz(snap, snaps_dir / f"fluid_{s:06d}.npz")
    snapshots.append(snap)

print(f"[3/5] {len(snapshots)} synthetic snapshots written → {snaps_dir}")

# ---------------------------------------------------------------------------
# 4. Produce visualisation plots
# ---------------------------------------------------------------------------
from lbm_post.plot import (
    plot_velocity_magnitude,
    plot_streamlines,
    plot_vorticity,
    plot_velocity_profile,
    plot_convergence,
    save_figure,
)
from lbm_post.analysis import monitor_point

final_snap = snapshots[-1]

fig, _ = plot_velocity_magnitude(final_snap)
save_figure(fig, OUTPUT_DIR / "velocity_magnitude.png")

fig, _ = plot_streamlines(final_snap)
save_figure(fig, OUTPUT_DIR / "streamlines.png")

fig, _ = plot_vorticity(final_snap)
save_figure(fig, OUTPUT_DIR / "vorticity.png")

fig, _ = plot_velocity_profile(
    final_snap,
    x_slices=[50],     # vertical profile at cavity centre x=50
    component="ux",
)
save_figure(fig, OUTPUT_DIR / "ux_profile.png")

# Time-series of ux at the cavity monitor point (50, 50)
monitor_steps, monitor_values = monitor_point(snapshots, xi=50, yj=50, field="ux")
fig, _ = plot_convergence(monitor_steps, monitor_values,
                           label="ux at (50,50)",
                           log_scale=False)
save_figure(fig, OUTPUT_DIR / "monitor_ux.png")

print(f"[4/5] Plots saved → {OUTPUT_DIR}")

# ---------------------------------------------------------------------------
# 5. Compute bulk statistics
# ---------------------------------------------------------------------------
from lbm_post.analysis import compute_bulk_quantities

bq = compute_bulk_quantities(final_snap)
print(f"[5/5] Bulk statistics at step {bq.step}:")
print(f"      KE        = {bq.ke:.6f}")
print(f"      Enstrophy = {bq.enstrophy:.6f}")
print(f"      ρ mean    = {bq.rho_mean:.6f}  std = {bq.rho_std:.2e}")
print(f"      max |∇·u| = {bq.div_max:.2e}")
print("\nDone.")
